name: Bug Report
description: Create a report to help us improve
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: wh
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: str
    attributes:
      label: Steps to reproduce
      description: How to reproduce this issue?
      placeholder:  |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: eb
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: gv
    attributes:
      label: Game Version
      description: What version of MGH are you running?
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What kind of operating systems are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Android
        - Linux
        - Mac-OS
    validations:
      required: false